# 这个文件是派蒙相关配置项的默认值，你可以在启动前将本文件复制一份，删除_default后缀，然后修改配置项。若不修改，启动后也会自动根据默认值生成一份文件。
# 你可以向机器人使用[pm set 配置名 配置值]来动态修改配置项。

启用CookieWeb: false
# 是否启用绑定Cookie的网页UI
CookieWeb地址: http://127.0.0.1:13579/LittlePaimon/cookie
# CookieWeb的地址，如要公网访问，请修改公网ip，如需使用nginx等反代，请参考https://pywebio.readthedocs.io/zh_CN/latest/misc.html?highlight=nginx#nginx-websocket-config-example进行配置

模拟抽卡群冷却: 30 # 群冷却时间，单位秒
模拟抽卡群成员冷却: 60 # 群成员冷却时间，单位秒

米游币自动获取开关: true # 是否自动获取米游币
米游币开始执行时间(小时): 8 # 开始执行没米游币自动获取的时间
米游币开始执行时间(分钟): 0 # 开始执行没米游币自动获取的时间

米游社自动签到开关: true # 是否开启米游社自动签到
米游社签到开始时间(小时): 0 # 开始执行没米游社原神自动的时间
米游社签到开始时间(分钟): 5 # 开始执行没米游社原神自动的时间

实时便签检查开关: true # 是否开启实时便签检查
实时便签检查间隔: 16 # 实时便签检查间隔，单位分钟
实时便签停止检查开始时间: 0
实时便签停止检查结束时间: 6 # 处于这个时间段的时候停止检查

# 浏览器内核设置
# 可选 chromium, firefox, webkit
# 默认使用firefox
browser_type: ''